### PR TITLE
100% Coverage for SocketsMonitor

### PR DESCRIPTION
**Pull request by rsandor**
cc: @podviaznikov

### CODE REVIEW

**Comment by podviaznikov** [comment]
@rsandor cool, thanks for adding that. I didn't know how to cover that case. Now I know

**Comment by rsandor** [comment]
Sinon is amazing :)

**Comment by bkendall** [comment]
what is the `1.0.1` commit? shouldn't that be incremented after this is merged?

**Comment by rsandor** [comment]
There is some git weirdness going on, that commit is already in master :/

**Comment by rsandor** [comment]
These changes start at bace7c5

**Pull request merged**
